#!/bin/sh
# -*-Julia-*-
#=
jlversion=""
if [[ "$1" == "+"* ]] ; then 
   jlversion=$1
   shift
fi
exec julia $jlversion --startup-file=no "$0" "$@"
=#
using JuliaFormatter
using ArgParse

function main(args)
    settings = ArgParseSettings()
    settings.description = "Format Julia code"
    settings.commands_are_required = false
    settings.add_version = true
    add_arg_table!(
        settings,
        "paths",
        Dict(:help => "Paths to format", :required => true, :nargs => '*'),
    )
    parsed_args = parse_args(args, settings)
    #    format_text("println(1+1)")
    paths=abspath.(parsed_args["paths"])
    println("formatting $(paths)... ")
    format(paths; verbose = true, overwrite=true)
    println("...done")
end


main(ARGS)
